Get http://localhost:8001/spending

###

Get http://localhost:8001/spending/f33c5a82-796c-4f8f-b4d9-080440adeb1f

###

POST http://localhost:8001/spending HTTP/1.1
Content-Type: application/json

{
  "amount": 20,
  "remark": "Sugar",
  "spending_date": "2023-10-01T00:00:00Z",
  "category_id": "f653fceb-f5f4-465d-95ab-dc383232a2a5"
}

###

Get http://localhost:8001/categories

###

Get http://localhost:8001/categories/e364f0eb-91fc-469c-9638-d57da27c1452

###

POST http://localhost:8001/categories HTTP/1.1
Content-Type: application/json

{
  "name": "Dinning"
}

###
Get http://localhost:8001/stores

###
POST http://localhost:8001/stores HTTP/1.1
Content-Type: application/json

{
  "categoryId": "f653fceb-f5f4-465d-95ab-dc383232a2a5",
  "name": "Wellcome"
}

###
