###
Get http://localhost:8001/api/spending
Headers:
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

###

Get http://localhost:8001/api/spending/f33c5a82-796c-4f8f-b4d9-080440adeb1f

###

POST http://localhost:8001/api/spending HTTP/1.1
Content-Type: application/json

{
  "amount": 20,
  "remark": "Salt",
  "spending_date": "2023-10-01T00:00:00Z",
  "category_id": "f653fceb-f5f4-465d-95ab-dc383232a2a5"
}

###

Get http://localhost:8001/api/categories

###

Get http://localhost:8001/api/categories/f653fceb-f5f4-465d-95ab-dc383232a2a5

###

POST http://localhost:8001/api/categories HTTP/1.1
Content-Type: application/json

{
  "name": "Home",
  "stores": [
    {
      "name": "HomeDepot"
    }
  ]
}

###
Get http://localhost:8001/api/stores

###
POST http://localhost:8001/api/stores HTTP/1.1
Content-Type: application/json

{
  "categoryId": "f653fceb-f5f4-465d-95ab-dc383232a2a5",
  "name": "Wellcome"
}

###

POST http://localhost:8001/api/receipts HTTP/1.1
Content-Type: application/json

{
  "storeName": "Wellcome",
  "totalAmount": 100.0,
  "date": "2023-10-01T00:00:00Z",
  "items": [
    {
      "name": "Apple",
      "price": 30.0
    },
    {
      "name": "Banana",
      "price": 20.0
    },
    {
      "name": "Orange",
      "price": 50.0
    }
  ]
}

###